### ISSUE TITLE
Team name and notation

### ISSUE THREAD

**Issue by mhdolatabadi** [comakestan/about#1]
Why do you write Comakestan instead its right notation Komakestan?

**Comment by machitgarha** [comment]
So, the question is: Which of the following notations is more suitable for our team's name?

**Comment by machitgarha** [comment]
Comakestan

**Comment by machitgarha** [comment]
Komakestan

**Comment by machitgarha** [comment]
Comackestan

**Comment by machitgarha** [comment]
Komackestan

**Comment by mhdolatabadi** [comment]
Komak-kade

**Comment by machitgarha** [comment]
Changed the name to Komakestan. Thanks for everyone contributing on this.

**Comment by mhdolatabadi** [comment]
Your welcome
